### ISSUE TITLE
Media Library field is currently borked

### ISSUE THREAD

**Issue by 0aveRyan** [WordPress-Phoenix/wordpress-options-builder-class#1]
🐛 Uploader needs updating to backbone from old wp core iframe method

**Comment by scarstens** [comment]
http://wordpress.stackexchange.com/questions/136698/adding-media-upload-to-custom-options-panel-breaks-insert-into-post

**Comment by scarstens** [comment]
or possible convert to https://github.com/stuttter/wp-term-images/blob/master/assets/js/term-image.js

**Comment by 0aveRyan** [comment]
Fixed in v2
